spring.application.name=HellTrain

#修改 server 啟動的 port，預設是 8080
#server.port=8083
#設定資料庫連接
# 3306是連接 mysql 的 port；p1141121 是要連接的資料庫名稱
# rewriteBatchedStatements=true: 可以批次新增
spring.datasource.url=jdbc:mysql://localhost:3306/our_helltrain?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=Asia/Taipei&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
spring.datasource.username=root
# 本地連線密碼防護機制，沒建這個檔案，系統就會直接跳過；有建的人就會自動套用本地密碼。
spring.profiles.include=local
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jackson.time-zone=Asia/Taipei

#sql schema 檔案來源: 創建表和欄位的語法，包含欄位名稱、資料型態、限制、預設值等
#spring.sql.init.schema-locations=classpath:schema-mysql.sql
#[always][embedded][never]

#如有資料表則spring.sql.init.mode=always需註解掉
#spring.sql.init.mode=always

#sql 測試資料來源: 新增測試資料的語法
#spring.sql.init.data-locations=classpath:data-mysql.sql

#會自動產生 table，但 schema 和 entity 要先建立
#spring.jpa.generate-ddl=false+

#寄送驗證碼給使用者信箱
#gmail共通設定
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#寄送端的信箱及 mail及應用程式密碼
#Google 為了安全性，不允許第三方程式直接用 Gmail 登入密碼，所以要另外產生一組專用密碼給應用程式使用
spring.mail.username=ershougo@gmail.com
spring.mail.password=fhbb uxye szhw knhx

#建立圖片存放資料夾
file.upload.path=${user.dir}/uploads/
#限制圖片檔的上限(全域)
spring.servlet.multipart.max-file-size=5MB 
spring.servlet.multipart.max-request-size=5MB 